require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/subtasks", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Subtask. As you add validations to Subtask, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Subtask.create! valid_attributes
      get subtasks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      subtask = Subtask.create! valid_attributes
      get subtask_url(subtask)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_subtask_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      subtask = Subtask.create! valid_attributes
      get edit_subtask_url(subtask)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Subtask" do
        expect {
          post subtasks_url, params: { subtask: valid_attributes }
        }.to change(Subtask, :count).by(1)
      end

      it "redirects to the created subtask" do
        post subtasks_url, params: { subtask: valid_attributes }
        expect(response).to redirect_to(subtask_url(Subtask.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Subtask" do
        expect {
          post subtasks_url, params: { subtask: invalid_attributes }
        }.to change(Subtask, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post subtasks_url, params: { subtask: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested subtask" do
        subtask = Subtask.create! valid_attributes
        patch subtask_url(subtask), params: { subtask: new_attributes }
        subtask.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the subtask" do
        subtask = Subtask.create! valid_attributes
        patch subtask_url(subtask), params: { subtask: new_attributes }
        subtask.reload
        expect(response).to redirect_to(subtask_url(subtask))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        subtask = Subtask.create! valid_attributes
        patch subtask_url(subtask), params: { subtask: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested subtask" do
      subtask = Subtask.create! valid_attributes
      expect {
        delete subtask_url(subtask)
      }.to change(Subtask, :count).by(-1)
    end

    it "redirects to the subtasks list" do
      subtask = Subtask.create! valid_attributes
      delete subtask_url(subtask)
      expect(response).to redirect_to(subtasks_url)
    end
  end
end
